spring:
  application:
    name: api-gateway

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: prometheus
# Zuul looks for Eureka (Netflix discovery service) by default.
# Once service are deployed, they are managed by Docker Swarm discovery service and Eureka is not used
ribbon:
  eureka:
    enabled: false

zuul:
  sensitiveHeaders:
  host:
    socket-timeout-millis: 180000
    connect-timeout-millis: 180000
  routes:
    favorites:
      path: /catalog-service/favorites/
      #url: forward:/catalog-service/favorites
    ml-description-based-recommendation-service:
      path: /ml-description-based-recommendation-service/**
    ml-team-2-service:
      path: /ml-team-2-service/**
    ml3-recommendation-service:
      url: /ml3-recommendation-service/**
    ml4-recommendation-service:
      url: /segandrec-service/**
    demo-service:
      path: /demo-service/**
    demo-catalog-service:
      path: /demo-catalog-service/**
    user-service:
      path: /user-service/**
      serviceId: user-service
    catalog-service:
      path: /catalog-service/**
    am-parser-service:
      path: /am-parser-service/**
    winelab-parser-service:
      path: /winelab-parser-service/**
    simple-parser-service:
      path: /simple-parser-service/**
    winestyle-parser-service:
      path: /winestyle-parser-service/**
    crossroad-parser-service:
      path: /crossroad-parser-service/**
    lenta-parser-service:
      path: /lenta-parser-service/**
    deployment-service:
      path: /deployment-service/**
    notification-service:
      path: /notification-service/**
  # ignore all services except ones that are explicitly mapped
  ignored-services: '*'

